# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logins', '0002_auto_20180615_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
