# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='commented_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='posted_by',
        ),
    ]
