# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall', '0002_auto_20180619_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='posted_under',
        ),
    ]
