# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20180628_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('in_campign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_locations', to='campaigns.Campaign')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='campign',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='campign',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
