# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20180628_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_campign',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='has_locations', to='campaigns.Campaign'),
        ),
    ]
