# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(related_name='has_campaigns', to='login_registration.User')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_registration.User')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('race', models.CharField(max_length=30)),
                ('subrace', models.CharField(blank=True, max_length=30, null=True)),
                ('char_class', models.CharField(max_length=30)),
                ('char_subclass', models.CharField(blank=True, max_length=50, null=True)),
                ('alignment', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('background', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('stats', picklefield.fields.PickledObjectField(editable=False)),
                ('skills', picklefield.fields.PickledObjectField(editable=False)),
                ('tools', picklefield.fields.PickledObjectField(editable=False)),
                ('equipment', picklefield.fields.PickledObjectField(editable=False)),
                ('personality', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('ideals', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('bonus', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spell_type', models.CharField(max_length=30)),
                ('cast_time', models.IntegerField()),
                ('cast_range', models.IntegerField()),
                ('components', picklefield.fields.PickledObjectField(editable=False)),
                ('duration', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='has_feats',
            field=models.ManyToManyField(related_name='used_by', to='dashboard.Feat'),
        ),
        migrations.AddField(
            model_name='character',
            name='has_spells',
            field=models.ManyToManyField(related_name='used_by', to='dashboard.Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='in_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_characters', to='dashboard.Campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='played_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_characters', to='login_registration.User'),
        ),
    ]
