# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='members',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='character',
            name='has_feats',
        ),
        migrations.RemoveField(
            model_name='character',
            name='has_spells',
        ),
        migrations.RemoveField(
            model_name='character',
            name='in_campaign',
        ),
        migrations.RemoveField(
            model_name='character',
            name='played_by',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Feat',
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
    ]
